const PRESETS = {
  default: [
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
  ],
  classic: [
    'binary2',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
  ],
  noisy: [
    'binary2',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
  ],
  hexlife: [
    'binary2',
    'binary23',
  ],
  rainbowRoad: [
    'fractalLeft',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
    'cycle',
  ]
};
