const PRESETS = {
  default: [
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
  ],
  classic: [
    'binary2',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
  ],
  noisy: [
    'binary2',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
  ],
  hexlife: [
    'binary2',
    'binary23',
  ],
  rainbowRoad: [
    'fractalLeft',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
  ],
  fancytownClassic: [
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
  ],
};
