dev:
    vue.js:
        - client/vendor/vue-dev.js
    hexularity.js:
        - src/hexular.js

        - client/rules.js
        - client/presets.js
        - client/app.js

prod:
    vue.js:
        - client/vendor/vue.js
    hexularity.js:
      - src/hexular.js
      - client/rules.js
      - client/presets.js
      - client/app.js