default:
  port: 8000
  files:
    client.js:
      - hexular/hexular.js
      - client/rules.js
      - client/presets.js
      - client/app.js
      - client/actions.js
    client.css:
      - client/vendor/icons.css
      - client/app.css
dev:
  files:
    vue.js:
      - client/vendor/vue-dev.js

prod:
  files:
    vue.js:
      - client/vendor/vue.js