default:
  port: 8000
  files:
    client.js:
      - hexular/hexular.js
      - client/classes/*.js
      - client/classes/modals/*.js
      - client/library/*.js
      - client/vendor/jscolor.js
      - client/app.js
      - plugins/*.js
    client.css:
      - client/icon-main.css
      - client/icon-defs.css
      - client/app.css
dev:
  files: {}

prod:
  files: {}
