default:
  port: 8000
  files:
    client.js:
      - hexular/hexular.js
      - client/preset.js
      - client/opt-parser.js
      - client/recorder.js
      - client/rule-menu.js
      - client/actions.js
      - client/modals.js
      - client/examples/rules.js
      - client/examples/presets.js
      - client/app.js
    client.css:
      - client/vendor/icons.css
      - client/app.css
dev:
  files: {}

prod:
  files: {}