const PRESETS = {
  default: new Preset([
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
    'ennead',
  ]),
  classic: new Preset([
    'binary2',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
    'classicDuplex23',
  ]),
  noisy: new Preset([
    'binary2',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
  ]),
  hexlife: new Preset([
    'binary2',
    'binary23',
  ]),
  rainbowRoad: new Preset([
    'fractalLeft',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
    'stepUp',
  ]),
  fancytownClassic: new Preset([
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
    'fancytown',
  ], {nh: 19}),
};