let PRESETS = {
  default: [
    'binary2',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
    'offset23',
  ],
  hexlife: [
    'binary2',
    'binary23',
  ],
  classic: [
    'binary2',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
    'offset23minus',
  ],
};
